export const QUERY_KEYS = {
  ADMIN_RENTS: "adminRents",
  ADMIN_RESERVATIONS: "adminReservations",
  ADMIN_REVIEWS: "adminReviews",
  ADMIN_RENT_DETAIL: "adminRentDetail",
  CATEGORIES: "categories",
  LOCATIONS: "locations",
  RESERVATIONS: "reservations",
  FEATURED_RENTS: "featuredRents",
  RENT_LIST: "rentList",
  RENT_DETAIL: "rentDetail",
  USER_CONVERSATION: "userConversation",
  ADMIN_CHAT: "adminChat",
  ADMIN_CONVERSATIONS: "adminConversations",
};
